### ISSUE TITLE
[Trilium] doesn't start

### ISSUE THREAD

**Issue by ShutdownRepo** [ShutdownRepo/Exegol-images#24]
Trilium fails to start.

```bash
[Jun 26, 2022 - 00:15:17 (CEST)] exegol-test /workspace # trilium-start                                                                              
Starting server on http://0.0.0.0:1991/
[1] 128
```
```
[Jun 26, 2022 - 00:15:20 (CEST)] exegol-test /workspace # 
[1]  + 128 exit 1     nohup node /opt/tools/trilium/src/www &> ~/.trilium.nohup.out
```
```
[Jun 26, 2022 - 00:18:20 (CEST)] exegol-test /workspace # node /opt/tools/trilium/src/www 
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'cls-hooked'
Require stack:
- /opt/tools/trilium/src/services/cls.js
- /opt/tools/trilium/src/services/log.js
- /opt/tools/trilium/src/app.js
- /opt/tools/trilium/src/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/tools/trilium/src/services/cls.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/tools/trilium/src/services/cls.js',
    '/opt/tools/trilium/src/services/log.js',
    '/opt/tools/trilium/src/app.js',
    '/opt/tools/trilium/src/www'
  ]
}
```

**Comment by ShutdownRepo** [comment]
Same problem as https://github.com/ShutdownRepo/Exegol-images/issues/27#issuecomment-1167145527
